// Created by iWeb 3.0.4 local-build-20150620

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,182),url:'Explore_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Explore_files/stroke_1.png'},{rect:new IWRect(1,-1,524,2),url:'Explore_files/stroke_2.png'},{rect:new IWRect(525,-1,2,2),url:'Explore_files/stroke_3.png'},{rect:new IWRect(525,1,2,182),url:'Explore_files/stroke_4.png'},{rect:new IWRect(525,183,2,2),url:'Explore_files/stroke_5.png'},{rect:new IWRect(1,183,524,2),url:'Explore_files/stroke_6.png'},{rect:new IWRect(-1,183,2,2),url:'Explore_files/stroke_7.png'}],new IWSize(526,184)),stroke_1:new IWEmptyStroke(),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,149),url:'Explore_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Explore_files/stroke_9.png'},{rect:new IWRect(1,-1,222,2),url:'Explore_files/stroke_10.png'},{rect:new IWRect(223,-1,2,2),url:'Explore_files/stroke_11.png'},{rect:new IWRect(223,1,2,149),url:'Explore_files/stroke_12.png'},{rect:new IWRect(223,150,2,2),url:'Explore_files/stroke_13.png'},{rect:new IWRect(1,150,222,2),url:'Explore_files/stroke_14.png'},{rect:new IWRect(-1,150,2,2),url:'Explore_files/stroke_15.png'}],new IWSize(224,151))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Explore_files/ExploreMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');fixAllIEPNGs('Media/transparent.gif');fixupAllIEPNGBGs();fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id12');fixupIECSS3Opacity('id13');applyEffects()}
