// Created by iWeb 3.0.4 local-build-20150620

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,243),url:'Support_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Support_files/stroke_9.png'},{rect:new IWRect(1,-1,898,2),url:'Support_files/stroke_10.png'},{rect:new IWRect(899,-1,2,2),url:'Support_files/stroke_11.png'},{rect:new IWRect(899,1,2,243),url:'Support_files/stroke_12.png'},{rect:new IWRect(899,244,2,2),url:'Support_files/stroke_13.png'},{rect:new IWRect(1,244,898,2),url:'Support_files/stroke_14.png'},{rect:new IWRect(-1,244,2,2),url:'Support_files/stroke_15.png'}],new IWSize(900,245)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,134),url:'Support_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Support_files/stroke_17.png'},{rect:new IWRect(1,-1,166,2),url:'Support_files/stroke_18.png'},{rect:new IWRect(167,-1,2,2),url:'Support_files/stroke_19.png'},{rect:new IWRect(167,1,2,134),url:'Support_files/stroke_20.png'},{rect:new IWRect(167,135,2,2),url:'Support_files/stroke_21.png'},{rect:new IWRect(1,135,166,2),url:'Support_files/stroke_22.png'},{rect:new IWRect(-1,135,2,2),url:'Support_files/stroke_23.png'}],new IWSize(168,136)),stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,225),url:'Support_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Support_files/stroke_25.png'},{rect:new IWRect(1,-1,684,2),url:'Support_files/stroke_26.png'},{rect:new IWRect(685,-1,2,2),url:'Support_files/stroke_27.png'},{rect:new IWRect(685,1,2,225),url:'Support_files/stroke_28.png'},{rect:new IWRect(685,226,2,2),url:'Support_files/stroke_29.png'},{rect:new IWRect(1,226,684,2),url:'Support_files/stroke_30.png'},{rect:new IWRect(-1,226,2,2),url:'Support_files/stroke_31.png'}],new IWSize(686,227)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,191),url:'Support_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Support_files/stroke_1.png'},{rect:new IWRect(1,-1,898,2),url:'Support_files/stroke_2.png'},{rect:new IWRect(899,-1,2,2),url:'Support_files/stroke_3.png'},{rect:new IWRect(899,1,2,191),url:'Support_files/stroke_4.png'},{rect:new IWRect(899,192,2,2),url:'Support_files/stroke_5.png'},{rect:new IWRect(1,192,898,2),url:'Support_files/stroke_6.png'},{rect:new IWRect(-1,192,2,2),url:'Support_files/stroke_7.png'}],new IWSize(900,193))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Support_files/SupportMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id1');fixupAllIEPNGBGs();fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id7');Widget.onload();fixupIECSS3Opacity('id12');fixupIECSS3Opacity('id13');applyEffects()}
function onPageUnload()
{Widget.onunload();}
