// Created by iWeb 3.0.4 local-build-20150620

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,172),url:'Prayer_Times_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Prayer_Times_files/stroke_1.png'},{rect:new IWRect(1,-1,723,2),url:'Prayer_Times_files/stroke_2.png'},{rect:new IWRect(724,-1,2,2),url:'Prayer_Times_files/stroke_3.png'},{rect:new IWRect(724,1,2,172),url:'Prayer_Times_files/stroke_4.png'},{rect:new IWRect(724,173,2,2),url:'Prayer_Times_files/stroke_5.png'},{rect:new IWRect(1,173,723,2),url:'Prayer_Times_files/stroke_6.png'},{rect:new IWRect(-1,173,2,2),url:'Prayer_Times_files/stroke_7.png'}],new IWSize(725,174)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,342),url:'Prayer_Times_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Prayer_Times_files/stroke_9.png'},{rect:new IWRect(1,-1,399,2),url:'Prayer_Times_files/stroke_10.png'},{rect:new IWRect(400,-1,2,2),url:'Prayer_Times_files/stroke_11.png'},{rect:new IWRect(400,1,2,342),url:'Prayer_Times_files/stroke_12.png'},{rect:new IWRect(400,343,2,2),url:'Prayer_Times_files/stroke_13.png'},{rect:new IWRect(1,343,399,2),url:'Prayer_Times_files/stroke_14.png'},{rect:new IWRect(-1,343,2,2),url:'Prayer_Times_files/stroke_15.png'}],new IWSize(401,344)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,129),url:'Prayer_Times_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Prayer_Times_files/stroke_17.png'},{rect:new IWRect(1,-1,836,2),url:'Prayer_Times_files/stroke_18.png'},{rect:new IWRect(837,-1,2,2),url:'Prayer_Times_files/stroke_19.png'},{rect:new IWRect(837,1,2,129),url:'Prayer_Times_files/stroke_20.png'},{rect:new IWRect(837,130,2,2),url:'Prayer_Times_files/stroke_21.png'},{rect:new IWRect(1,130,836,2),url:'Prayer_Times_files/stroke_22.png'},{rect:new IWRect(-1,130,2,2),url:'Prayer_Times_files/stroke_23.png'}],new IWSize(838,131))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Prayer_Times_files/Prayer_TimesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');fixupAllIEPNGBGs();fixupIECSS3Opacity('id1');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id10');applyEffects()}
