// Created by iWeb 3.0.4 local-build-20150619

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_4:new IWStrokeParts([{rect:new IWRect(-1,1,2,163),url:'Home_X_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Home_X_files/stroke_25.png'},{rect:new IWRect(1,-1,252,2),url:'Home_X_files/stroke_26.png'},{rect:new IWRect(253,-1,2,2),url:'Home_X_files/stroke_27.png'},{rect:new IWRect(253,1,2,163),url:'Home_X_files/stroke_28.png'},{rect:new IWRect(253,164,2,2),url:'Home_X_files/stroke_29.png'},{rect:new IWRect(1,164,252,2),url:'Home_X_files/stroke_30.png'},{rect:new IWRect(-1,164,2,2),url:'Home_X_files/stroke_31.png'}],new IWSize(254,165)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,53),url:'Home_X_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Home_X_files/stroke_17.png'},{rect:new IWRect(1,-1,135,2),url:'Home_X_files/stroke_18.png'},{rect:new IWRect(136,-1,2,2),url:'Home_X_files/stroke_19.png'},{rect:new IWRect(136,1,2,53),url:'Home_X_files/stroke_20.png'},{rect:new IWRect(136,54,2,2),url:'Home_X_files/stroke_21.png'},{rect:new IWRect(1,54,135,2),url:'Home_X_files/stroke_22.png'},{rect:new IWRect(-1,54,2,2),url:'Home_X_files/stroke_23.png'}],new IWSize(137,55)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,53),url:'Home_X_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Home_X_files/stroke_1.png'},{rect:new IWRect(1,-1,215,2),url:'Home_X_files/stroke_2.png'},{rect:new IWRect(216,-1,2,2),url:'Home_X_files/stroke_3.png'},{rect:new IWRect(216,1,2,53),url:'Home_X_files/stroke_4.png'},{rect:new IWRect(216,54,2,2),url:'Home_X_files/stroke_5.png'},{rect:new IWRect(1,54,215,2),url:'Home_X_files/stroke_6.png'},{rect:new IWRect(-1,54,2,2),url:'Home_X_files/stroke_7.png'}],new IWSize(217,55)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,53),url:'Home_X_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Home_X_files/stroke_9.png'},{rect:new IWRect(1,-1,131,2),url:'Home_X_files/stroke_10.png'},{rect:new IWRect(132,-1,2,2),url:'Home_X_files/stroke_11.png'},{rect:new IWRect(132,1,2,53),url:'Home_X_files/stroke_12.png'},{rect:new IWRect(132,54,2,2),url:'Home_X_files/stroke_13.png'},{rect:new IWRect(1,54,131,2),url:'Home_X_files/stroke_14.png'},{rect:new IWRect(-1,54,2,2),url:'Home_X_files/stroke_15.png'}],new IWSize(133,55)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Home_X_files/Home_XMoz.css')
adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');fixupIECSS3Opacity('id1');fixupIECSS3Opacity('id2');fixupIECSS3Opacity('id3');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');applyEffects()}
